version: '3'
volumes:
    krb5kdc-data:
services:
  app:
    build: app
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos
    depends_on: 
      - "db2"
    networks:
      krbnet:
        ipv4_address: 10.4.0.3
    container_name: app
    volumes:
      - ./trace/app/jcc:/jcc
  db2:
    build: db2
    ports:
      - "50000:50000"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=kerberos
    privileged: True
    depends_on: 
      - "kerberos"
    networks:
      krbnet:
        ipv4_address: 10.4.0.5
  kerberos:
    build: kdc-server
    ports:
      - "99:99"
      - "464:464"
      - "749:749"
    environment:
      - KRB5_REALM=EXAMPLE.COM
      - KRB5_KDC=localhost
      - KRB5_PASS=password
    volumes:
      - krb5kdc-data:/var/lib/krb5kdc
    networks:
      krbnet:
        ipv4_address: 10.4.0.9
networks:
  krbnet:   
    ipam:
      config:
        - subnet: 10.4.0.0/16